language: python
sudo: false
cache:
  directories:
  - "$HOME/.pip-cache/"
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
python:
- '3.7'
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
install:
- pip wheel -r requirements.txt
- pip install .
- pip install coveralls>=1.1
script: pytest
after_success:
- coveralls
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: YVz+D5L8nbZOMiP/yVZ2TwcEUV4wSQEz3ZfG6C+Rcm1S2WttCNqH22aKI28Jq+HrdIMqMf4e8ozg1CrpYZKt4h84BFQWWSLlE3453yfWmBRFcWNWeLfzUxa0kPBgZkPVNDd5t+3PQnNNN0FX0+Muz943k0Bnzs6bBYukUopdlOs4MnAUWHPU98UtXT3pghaQ+ncB0szBKyRojeC1ADQWZuL7t2N/793tA24lKeHxHxogi5R80jI9W5vz6VYGfkwn8LcIZnub9nlkuyVcTHT663EiTXdlUflNvE49nvnxAFiaS7UpkrhnLDJFXos5jXSoq0fAU2GWLY2WcHkgnyS+0yjLMwiK3A8CqspK5CIAfYPKYrh54B7LNubPPpp2QiIKfI44zEUwWhMNrS2Ur9ejWcnEtsMyYFPObrCQnWy9sppUBx50q+peMWTcSZDX67z9MRN5S58v7XNjEuEPdLJiFNNhaFcgZ8weZEN4wKtxEjjvbQ6fOBvTMy6kPhbrbKPsqdMAxl7quOdDqP1TV48WRNet89/2pX8hE8T7meMw5eXt5F+wu+i5oXn4Pzr8xhPDIOW8Tx6aWJrMjYLqu7aDY7R4INM8rb37QppbVKeY4mcZ+c/iGUbommwvNawnjeD1g5skVd4DbWs+xTLubyCdQJUo5MhX38tCw7bGAPmYoZc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: mrahnis/surficial
  skip_cleanup: true
