language: python
sudo: false
cache:
  directories:
  - "$HOME/.pip-cache/"
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
python:
- '3.6'
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
install:
- pip wheel -r requirements.txt
- pip install .
- pip install coveralls>=1.1
script: pytest
after_success:
- coveralls
deploy:
  provider: pypi
  user: mrahnis
  password:
    secure: muNUqzX280qk7cMWZwhKA7U6cftBcSMfsgZGQU8gGgkQYB8FlL1DSeQy6HHK2cmHvNMHSMtH7O2AtHrOD5HihQLBe023If30klCgoX+d2M0cBD5II5idugakj87BkoT/pSM9OucPsaSKd/2ytzaA6aRescd0ost2bP9P2hZ2Jcml5howsbpjo+3aBTef63znU64rN0REYV0yn3unxXCI6AHznIKC6Q0ADB9rfzPwPR37Vh7j5v23PJSZ66KNlfk8emvAxwo3L9rwFHGGdQA6S7tH6gXxlMWr6HKW9rWbQ+0OHEmngxFMhTnln751TAglt4piWR3o41BrOyxCLSsB4VQspzkMhYjqKBpWkdbTiRyVMbllJHH6PxZk4UVLrJ0KYIEtQ5s3S+JsOfVQa4oFw/GBtaPkqnHriSHLVoNLLcLnTbiFCTLgOW9LoH0RubTeH/XfRvXnU8h5lWAIneoOnfMwt3S6EhcIoKRiAqvDTG5MNWM5gYK+0jlGwVOHGDSsCd4neK0zW9D/+43GkRBlJpLrvQ4hrUVw+Tnv5snOjyQGkzs65gChcB4wnhVAsgZnuYkBKVy5GhdvpVtxodLhE/Sks3EcVvbABZyHhfdTO4OhzyLEJ5vKVirYQhU7Umg20ohIaR+elaAi5cJEBW6DueiHswm+R2POTzdPKBfATxw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: mrahnis/surficial
  skip_cleanup: true
