[project]
name = "surficial"
version = "0.1.0"
description = "Add a short description here"
authors = ["mrahnis <mrahnis@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
adjusttext = ">=1.0.4,<1.1"
descartes = ">=1.1.0,<1.2"
shapely = ">=2.0.2,<2.1"
pandas = ">=2.1.4,<2.2"
python = ">=3.12.1,<3.13"
rasterio = ">=1.3.9,<1.4"
matplotlib = ">=3.8.2,<3.9"
fiona = ">=1.9.5,<1.10"
click = ">=8.1.7,<8.2"
pyproj = ">=3.6.1,<3.7"
networkx = ">=3.2.1,<3.3"
pip = ">=23.3.2,<23.4"
setuptools = ">=69.0.3,<69.1"
