{% set pyproject = load_file_data('pyproject.toml') %}
{% set version = pyproject.get('project').get('version') %}

package:
  name: surficial
  version: {{ version }}

source:
  git_url: https://github.com/mrahnis/surficial.git
  git_rev: HEAD

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - surficial = surficial.cli.surficial:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - click
    - pandas
    - matplotlib
    - shapely
    - descartes
    - rasterio
    - fiona
    - pyproj
    - networkx
    - adjusttext
    - drapery

test:
  imports:
    - surficial
  commands:
    - surficial --help

about:
  home: https://github.com/mrahnis/surficial
  description: Python library and CLI tools to support analysis of stream long-profiles
  license: BSD
  license_file: LICENSE.txt

# https://github.com/conda/conda-build/issues/4807
# whatever_you_do_don't_load_setup_py_dataxxx!!!
