package:
  name: surficial
  version: "0.0.2"

source:
  git_url: https://github.com/mrahnis/surficial.git
  git_rev: head

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - surficial = surficial.cli.surficial:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - click
    - pandas
    - matplotlib
    - shapely
    - descartes
    - rasterio
    - fiona
    - networkx
    - adjusttext
    - drapery

test:
  imports:
    - surficial
  commands:
    - surficial --help

about:
  home: https://github.com/mrahnis/surficial
  description: Python library and CLI tools to support analysis of stream long-profiles
  license: BSD
  license_file: LICENSE.txt